### ISSUE TITLE
Demo is slow

### ISSUE THREAD

**Issue by andreasala98** [andreasala98/NM4PIG#11]
I noticed Demo mode is quite slow when rendering images with the PathTracer...
Why don't we try to implement ```Trace.ImageTracer.fireAllRays``` in **parallel**? This should boost our code speed while maintaining the correct result.

**Comment by TommasoArmadillo** [comment]
Great idea @andreasala98. In C# this is very simple to implement since the language naturally implements parallelization. In `System.Threading.Tasks` there is the method `Parallel.For(int from, int to, Action<T>)` that executes in parallel the code for different values of the index. We could parallelize the outer loop, i.e. the one for rows
