### ISSUE TITLE
Cylinder Image Pigment

### ISSUE THREAD

**Issue by andreasala98** [andreasala98/NM4PIG#18]
Hey, 
I think Top and Bottom faces of Cylinder UV mapping are not working properly...
[Here](https://github.com/andreasala98/NM4PIG/blob/render/NM4PIG/CokeCanG.jpg)'s an example. @TommasoArmadillo did you look into these as well when you were fixing the UV mapping for cylinders?

**Comment by TommasoArmadillo** [comment]
Hi @andreasala98! I deeply look into the uv mapping for cylinders and the problem was that for the `HdrImage` class, the pixel (0,0) was the one in the top left corner, while in the UV mapping for cylinders I mapped (0,0) into the bottom left corner. Now everything works just fine and there is also no more the upside down effect you noticed. [Here](https://github.com/andreasala98/NM4PIG/blob/render/NM4PIG/Examples/Demo/doubleCokeCan.jpg) you can see that the mapping is working properly.

The image has been obtained with
`dotnet run -- demo --scene 2 --luminosity 2 --render-type f`
